name: 'Terraform'

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Plan (on PR only)
        if: github.event_name == 'pull_request'
        run: terraform plan -input=false

      - name: Terraform Apply (on push to main only)
        if: github.event_name == 'push'
        run: terraform apply -auto-approve -input=false
